---
- name: homework
  hosts: all
  become: yes
  tasks:
  - name: Add a user
    user:
      name: user
      state: present
  - name: Add a group
    group:
      name: agents
      state: present
  - name: Add to group
    user: 
      name: user
      groups:
      - docker
      - sudo
      - agents
      append: yes

  - name: Generate SSH key
    community.crypto.openssh_keypair:
      path: /home/user/.ssh/id_ed25519
     # passphrase: super_secret_password
      type: ed25519
      owner: user
      group: agents
    register: key_result

  - name: Set public SSH key variable
    ansible.builtin.set_fact:
      public_ssh_key: "{{ key_result.public_key }}"

  - name: Copy SSH public key
    ansible.posix.authorized_key:
      user: user
      state: present
      key: "{{ hostvars['public_ssh_key'] }}"
