version: '3.7'

volumes:
  postgres-data:

services:
  postgres:
    image: timescale/timescaledb-postgis:1.7.1-pg10
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "53222:5432"
    secrets:
      postgres_password:
        file: ./secrets/postgres_password.txt
    volumes:
      - postgres-data:/var/lib/postgresql/data
    shm_size: '2gb'
    logging:
      options:
        max-size: "50M"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: somesecretpassword
