---
- name: SSH key
  hosts: localhost
  tasks:
    - name: Generate random password
      shell: "openssl rand -base64 15 | tr -dc 'A-Za-z0-9' | head -c 20"
      register: generated_password
    
    - name: Generate SSH key
      command: ssh-keygen -t ecdsa -b 521 -f ~/.ssh/private_key -N "{{ generated_password.stdout }}" 
      args:
        creates: ~/.ssh/private_key

     
    - name: Save pass
      copy:
        content: "{{ generated_password.stdout }}"
        dest: ~/password.txt
        mode: '0600'
