---
- name: homework
  hosts: all
  become: yes
  tasks:
  - name: Add a user
    user:
      name: user
      state: present
  - name: Add a group
    group:
      name: agents
      state: present
  - name: Add to group
    user:
      name: user
      groups: docker,sudo,agents
      append: yes

 
